#! /bin/sh
#

# PROVIDE: doom
# KEYWORD: shutdown

. /etc/rc.subr

name="doom"
rcvar="doom_enable"

: ${doom_enable:="NO"}

doom_chdir="/home/hugh/odamex-src-0.8.3"
WAD_DIR="/home/hugh/wad"
logfile="/var/log/${name}.log"
PWAD="${WAD_DIR}/nb_e1m01.WAD"
IWAD="${WAD_DIR}/DOOM2.WAD"

command="/usr/sbin/daemon"
command_args="-u hugh -o ${logfile} ${doom_chdir}/server/odasrv -iwad ${IWAD} -file ${PWAD} -config /home/hugh/.odamex/dm-doom.cfg"



load_rc_config $name
run_rc_command "$1"
