#! /bin/sh
#

# PROVIDE: youtube_dl_api
# KEYWORD: shutdown

. /etc/rc.subr

name="youtube_dl_api"
rcvar="youtube_dl_api_enable"

: ${youtube_dl_api_enable:="NO"}

logfile="/var/log/${name}.log"
# Set up environment
PORT=9835  # YTDL
TOKEN="$(cat /data/token.txt)"
EXTHOST="https://hughscloud.com:$PORT"
FORMAT="%(title)s - %(uploader)s - %(id)s.%(ext)s"

command="/usr/sbin/daemon"
command_args="-u media -o $logfile /usr/local/bin/python /data/youtube-dl-api/youtube-dl-api.py"



load_rc_config $name
run_rc_command "$1"
