#! /bin/sh
#

# PROVIDE: youtube_dl_api
# KEYWORD: shutdown

. /etc/rc.subr

name="youtube_dl_api"
rcvar="youtube_dl_api_enable"

: ${youtube_dl_api_enable:="NO"}

logfile="/var/log/${name}.log"
# Set up environment
export PORT=9835  # YTDL
export TOKEN="$(cat /data/token.txt)"
export EXTHOST="http://hughscloud.com:$PORT"
export FORMAT="%(title)s - %(uploader)s - %(id)s.%(ext)s"
export PATH="${PATH}:/usr/local/bin"

command="/usr/sbin/daemon"
command_args="-o $logfile /usr/local/bin/python /data/youtube-dl-api/youtube-dl-api.py"



load_rc_config $name
run_rc_command "$1"
